#pragma once

#include "wog2/misc.h"

struct ParticleEffectInfoIndexInfo {
    char uuid[64];
    int field_0x40;
};

struct OpaqueTokenAnimHandle {
};

struct BallAttenuationFunctionInfo {
    PackedArray<float> frames;
    float totalLength;
    int field_0x94;
    int field_0x98;
    int field_0x9c;
};

struct ImageIdInfo {
    char imageId[0x40];
};

// Exported from Ghidra
// TODO: improve documentation on some things
struct BallTemplateInfo {
    char name[64];
    float width;
    float height;
    int ballShape;
    float sizeVariance;
    float mass;
    float towerMass;
    float dragMass;
    float destroyForce;
    float maxDropDistance;
    int maxStrands;
    float walkSpeed;
    float climbSpeed;
    float speedVariance;
    float antiGravFactor;
    bool isAntiGravAttached;
    bool isAntiGravUnattached;
    float dampening;
    float rotationalDampening;
    bool isEditable;
    bool isDraggable;
    bool isDetachable;
    bool diesOnDetach;
    bool isInvulnerable;
    bool isInvulerableToLava;
    bool isStickyAttached;
    bool isStickyUnattached;
    bool attachToSameTypeOnly;
    bool isGrumpy;
    bool isStatic;
    bool isStaticWhenSleeping;
    float selectionMarkerRadius;
    bool countMoveOnUnattachedRelease;
    int attachedMarginSS;
    int unattachedMarginSS;
    int health;
    int color;
    float jumpMultiplierMin;
    float jumpMultiplierMax;
    bool collideAttached;
    bool collideWithAttached;
    bool collideWithParticlesAttached;
    int collisionGroup;
    bool allowAttachmentsWhenStuck;
    bool allowAttachmentsWhenFalling;
    float motorMaxForce;
    float motorMaxForceUndiscovered;
    bool isSuckable;
    bool opensExitUnattached;
    bool affectsAutoboundsAttached;
    bool affectsAutoboundsUnattached;
    float burnTime;
    float detonateForce;
    float detonateRadius;
    bool detonateKillBalls;
    bool detonateKillItems;
    bool detomateKillTerrain;
    ParticleEffectInfoIndexInfo detonateParticleEffect;
    bool autoAttach;
    bool isClimber;
    float attachedParticleBarrierFactory;
    char field_0x124[64];
    int field_0x164;
    int contains;
    int field_0x16c[0x43];
    int soundId;
    int field_0x27c[15];
    char popParticlesId[256];
    bool despawnTriggersFullDeath;
    ParticleEffectInfoIndexInfo deathParticleEffect;
    ParticleEffectInfoIndexInfo fireworksParticleEffect;
    char trailEffectId[64];
    ParticleEffectInfoIndexInfo trailParticleEffect;
    bool trailEffectEnabled;
    float popDuration;
    float popDelayMin;
    float popDelayMax;
    bool hideEyes;
    bool botoxEyesWhenAttached;
    bool isBehindStrands;
    float wakeOtherBallsAtDistance;
    int spawnType;
    float decay;
    float flingForceFactor;
    float flingStrandMaxLength;
    bool autoDisable;
    float maxDragForce;
    float dragDampeningFactor;
    bool alwaysLookAtMouse;
    bool hingeDrag;
    float maxAttachSpeed;
    bool jumpOnWakeup;
    float thrust;
    bool useDistantSounds;
    bool canBeRotatedByHand;
    int stencil;
    bool stencilWhenAttached;
    bool canSuckLiquidExternally;
    bool canSuckLiquidFromPipe;
    int liquidParticlesPerSecond;
    int initialBallLiquidAmount;
    float maxBallLiquidAmount;
    float maxStrandLiquidAmount;
    float liquidSinkOffset;
    int field_0x52c;
    float field_0x530;
    int strandType;
    float field_0x538[14];
    bool field_0x570[7];
    ImageIdInfo strandImageId;
    ImageIdInfo strandInactiveImageId;
    ImageIdInfo strandInactiveOverlayImageId;
    char field_0x637;
    float field_0x638[2];
    char field_0x640[64];
    ImageIdInfo strandBurntImageId;
    ImageIdInfo strandBackgroundImageId;
    ImageIdInfo detachStrandImageId;
    float field_0x740;
    ImageIdInfo dragMarkerImageId;
    ImageIdInfo detachMarkerImageId;
    float markerRotSpeed;
    int stainLiquidType;
    int field_0x7cc;
    BallAttenuationFunctionInfo deselectAttenuationFunc;
    BallAttenuationFunctionInfo selectAttenuationFunc;
    BallAttenuationFunctionInfo dropAttenuationFunc;
    BallAttenuationFunctionInfo dragAttenuationFunc;
    BallAttenuationFunctionInfo spawnAttenuationFunc;
    int ballParts;
    int field_0xaf4[0x5303];
    int bodyPart;
    int field_0x15704[0x10];
    int stateAnimations;
    int field_0x15748[0x96c3];
    int splatImageIds;
    int field_0x3b258[0x83];
    int soundEvents;
    int field_0x3b468[0x40c4];
    int flashAnimation;
    int field_0x4b77c[15];
    OpaqueTokenAnimHandle** unk;
    int flashAnimationPreLiquidLayerTextureIndices;
    int field_0x4b7c4[7];
    int stateScales;
    int field_0x4b7e4[0x16];
    int particleEffects;
    int field_0x4b840[0x1d3];
    int stableFluidsDensityFactor;
    float stableFluidsMinTrailVelocity;
    int stableFluidsDensityRange;
    int field_0x4bf98;
    bool field_0x4bf9c[2];
    float field_0x4bfa0;
    bool field_0x4bfa4[4];
    int popSpawnItems;
    int field_0x4bfac[0x8b];
    float popSpawnItemProbability;
    int popSpawnItemCountRange;
    int field_0x4c1e0;
    int popSpawnItemRadiusRange;
    int field_0x4c1e8;
    int popSpawnItemScaleRange;
    int field_0x4c1f0;
    int strandShatterItem;
    int field_0x4c1f8[0x10];
    float strandShatterItemProbability;
    int strandShatterParticleEffect;
    int field_0x4c240[0x10];
    float strandShatterParticleEffectProbability;
    float strandShatterFragmentSize;
    float unwalkableTime;
    float dynamicLightingFactor;
    float attachedDynamicLightingFactor;
    float undiscoveredDynamicLightingFactor;
    bool field_0x4c298;
    int field_0x4c29c[2];
    bool field_0x4c2a4[6];
    int field_0x4c2ac;
    int thrusterStableFluidsImag;
    int field_0x4c2b4[0x11];
    int markerColor;
    float field_0x4c2fc[4];
    int structureFillingLayers;
    int field_0x4c310[0x14b];
    float field_0x4c83c[4];
    int field_0x4c84c;
    int laserGradientStart;
    int laserGradientEnd;
    ImageIdInfo laserOverrideImage;
    int field_0x4c898[0xac];
    
public:
    inline bool isInitialized() const {
        return name[0] != '\0';
    }
};

static_assert(sizeof(BallTemplateInfo) == 0x4cb48);
